spark.master                     yarn
spark.driver.memory              1g
spark.yarn.am.memory             1g
spark.executor.memory            1g
spark.executor.instances         1
spark.sql.warehouse.dir          /user/hive/warehouse
spark.sql.hive.metastore.version 3.1.3
spark.sql.hive.metastore.jars    path